name: chanos
title: chanos record
description: 
tags:
  - dotnet
  - csharp
  - asp.net core
  - c#
  - .net
  - .net core
  - .net framework  
  - winform
  - webapi
  - blazor
  - mvc
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Category
    url: /categorylist
  - title: Tags
    url: /tags
  - title: Feed
    url: /feed.xml
email: chanos-dev@gmail.com
# paginate: 12
# See: https://disqus.com/
# disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
# formspree_form_id: formspree_form_id
